CXX = g++ --std=c++20 
VPATH = ./src:./src/track_graph:./src/graphics/
RAYLIB_DIR = ./raylib/src/

# This allows the preprocessor to also generate the dependencies in the *.d files
CPPFLAGS += -MP -MD

CXXBASEFLAGS = -Wall -Wextra
DEBUGFLAGS = -g3 -fsanitize=address
RELEASEFLAGS = -flto -O3 -DNDEBUG

MODE ?= DEBUG# Default is Debug, any other value will build for release

# Raylib has some warnings that we don’t want to see when compiling in debug
RAYLIB_IGNORE_WARNINGS = -Wno-unused-result -Wno-unused-but-set-variable
ifeq ($(MODE),DEBUG)
	CXXFLAGS = $(CXXBASEFLAGS) $(DEBUGFLAGS)
	CUSTOM_CFLAGS = $(RAYLIB_IGNORE_WARNINGS) $(DEBUGFLAGS)
else
	CXXFLAGS = $(CXXBASEFLAGS) $(RELEASEFLAGS)
	CUSTOM_CFLAGS = $(RELEASEFLAGS)
endif

default: hexattd

# for raylib
RAYLIB_RELEASE_PATH = ../../
export CUSTOM_CFLAGS
export RAYLIB_RELEASE_PATH

SOURCES = main.cpp grid.cpp hex.cpp rail.cpp base.cpp vector.cpp display_track.cpp tile.cpp track_graph.cpp track_union_find.cpp train.cpp display_train.cpp
DEPENDS = main.o grid.o hex.o  rail.o base.o vector.o display_track.o tile.o track_graph.o track_union_find.o train.o display_train.o

# We include the autogenerated dependencies
-include $(SOURCES:%.cpp=%.d)

hexattd: $(DEPENDS) libraylib.a
	$(CXX) $(CXXFLAGS) -o $@ $^ $(DEPS) 

libraylib.a:
	$(MAKE) -C $(RAYLIB_DIR)

clean: clean_hex

cleanall : clean clean_raylib

clean_hex:
	rm -f ./hexattd
	rm -f *.o
	rm -f *.d

clean_raylib:
	$(MAKE) clean -C $(RAYLIB_DIR)
