#! /bin/bash

CXX = g++ --std=c++20 
VPATH = ./src:./src/track_graph:./src/graphics/:./build
NAME = hexattd

RAYLIB_DIR ?= ./raylib/src/
RAYGUI_DIR ?= ./raygui/src/

BUILD_DIR ?= ./build

# This allows the preprocessor to also generate the dependencies in the *.d files
CPPFLAGS += -MP -MD

CXXFLAGS = -Wall -Wextra -I$(RAYLIB_DIR) -I$(RAYGUI_DIR)
DEBUGFLAGS = -g3 -fsanitize=address
RELEASEFLAGS = -flto -O3 -DNDEBUG

MODE ?= RELEASE# Default is Release

# Raylib has some warnings that we don’t want to see when compiling in debug
CUSTOM_CFLAGS = -Wno-unused-result -Wno-unused-but-set-variable

# Allow usage of mold linker for faster build time, default to false
USE_MOLD_LINKER ?= FALSE
ifeq ($(USE_MOLD_LINKER), TRUE)
	LDFLAGS += -fuse-ld=mold
endif

ifeq ($(MODE),DEBUG)
	CXXFLAGS += $(DEBUGFLAGS)
	CUSTOM_CFLAGS += $(DEBUGFLAGS)
else
	CXXFLAGS += $(RELEASEFLAGS)
	CUSTOM_CFLAGS += $(RELEASEFLAGS)
endif

ifndef ECHO
T := $(shell $(MAKE) $(MAKECMDGOALS) --no-print-directory \
      -nrRf $(firstword $(MAKEFILE_LIST)) \
      ECHO="COUNTTHIS" | grep -c "COUNTTHIS")

N := x
C = $(words $N)$(eval N := x $N)
ECHO = echo -e "[$(C)/$(T)]"
endif

VERBOSE ?= FALSE

default: $(NAME)

# for raylib
RAYLIB_RELEASE_PATH = $(CURDIR)/$(BUILD_DIR)
LIBRAYLIB = $(BUILD_DIR)/libraylib.a
export CUSTOM_CFLAGS
export RAYLIB_RELEASE_PATH

SOURCES = $(notdir $(wildcard ./src/*.cpp ./src/track_graph/*.cpp ./src/graphics/*.cpp))
OBJECTS = $(addprefix $(BUILD_DIR)/, $(SOURCES:%.cpp=%.o))
MAKEFILES = $(OBJECTS:%.o=%.d)

# We include the autogenerated dependencies
-include $(MAKEFILES)

$(NAME): $(OBJECTS) $(LIBRAYLIB)
	@$(ECHO) "\033[32mBuilding executable $@ in $(MODE) mode\033[0m"
	@$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(BUILD_DIR)
	@$(ECHO) "\033[32mBuilding CXX object $@ in $(MODE) mode\033[0m"
	@$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c -o $@ $<

$(LIBRAYLIB):
	@mkdir -p $(BUILD_DIR)
	@$(ECHO) "\033[32mBuilding raylib static lib in $(MODE) mode, this job is longer than others...\033[0m"
	@$(MAKE) -C $(RAYLIB_DIR)

clean: clean_hex

cleanall : clean clean_raylib

clean_hex:
	$(RM) $(NAME)
	$(RM) $(OBJECTS)
	$(RM) $(MAKEFILES)
	$(RM) $(LIBRAYLIB)
	$(RM) --dir $(BUILD_DIR)

clean_raylib:
	$(MAKE) clean -C $(RAYLIB_DIR)

.PHONY: clean cleanall clean_hex clean_raylib
